version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    restart: no
    environment:
      MYSQL_DATABASE: campusfinder
      MYSQL_ROOT_PASSWORD: Aa949841!
      TZ: Asia/Seoul
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql  # 볼륨 설정 추가
    networks:
      - docker-bridge

  redis:
    container_name: redis
    image: redis
    restart: no
    ports:
      - "6379:6379"
    networks:
      - docker-bridge

networks:
  docker-bridge:
    driver: bridge

volumes:
  mysql-data:  # 볼륨 정의 추가
